apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: sno01-tn-telco-ocp-run
  namespace: sno01-tn-telco-ocp-run
  annotations:
    agent-install.openshift.io/install-config-overrides: '{"networking":{"networkType":"OVNKubernetes"}}'
spec:
  clusterDeploymentRef:
    name: sno01-tn-telco-ocp-run
  imageSetRef:
    name: openshift-v4.9.5
  networking:
    clusterNetwork:
      - cidr: "10.96.0.0/16"
        hostPrefix: 23
    serviceNetwork:
      - "172.97.0.0/16"
    machineNetwork:
      - cidr: "192.168.11.0/24"
  provisionRequirements:
    controlPlaneAgents: 1
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDst3pB7hKcKLvq2P7vON4OKgUZDInk9zEu/Kz2ruh/D kskels@redhat.com"
