apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: sno01-tn-telco-ocp-run
  namespace: sno01-tn-telco-ocp-run
spec:
  baseDomain: tn.telco.ocp.run
  clusterName: sno01
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: sno01-tn-telco-ocp-run
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: "sno01"
  pullSecretRef:
    name: pull-secret
