apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: sno01-tn-telco-ocp-run
  namespace: sno01-tn-telco-ocp-run
spec:
  applicationManager:
    argocdCluster: false
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    name: sno01-tn-telco-ocp-run
    cloud: Baremetal
    vendor: Libvirt 
  clusterName: sno01-tn-telco-ocp-run
  clusterNamespace: sno01-tn-telco-ocp-run
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  version: 2.2.0
