apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: sno01-tn-telco-ocp-run
  namespace: sno01-tn-telco-ocp-run
  labels:
    name: sno01-tn-telco-ocp-run
    pao: "false"
    sriov: "false"
    sno: "true"
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
