apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: sriov48-icsp
spec:
  repositoryDigestMirrors:
  - mirrors:
    - quay.io/alosadag/openshift4-ose-sriov-network-webhook
    source: registry.redhat.io/openshift4/ose-sriov-network-webhook
  - mirrors:
    - quay.io/alosadag/rh-osbs-openshift-ose-ptp-operator-bundle
    source: registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-ptp-operator-bundle
  - mirrors:
    - quay.io/alosadag/openshift4-ose-kube-rbac-proxy
    source: registry.redhat.io/openshift4/ose-kube-rbac-proxy
  - mirrors:
    - quay.io/alosadag/openshift4-ose-sriov-network-operator
    source: registry.redhat.io/openshift4/ose-sriov-network-operator
  - mirrors:
    - quay.io/alosadag/openshift4-ose-ptp-operator
    source: registry.redhat.io/openshift4/ose-ptp-operator
  - mirrors:
    - quay.io/alosadag/openshift4-ose-sriov-cni
    source: registry.redhat.io/openshift4/ose-sriov-cni
  - mirrors:
    - quay.io/alosadag/openshift4-ose-sriov-operator-must-gather
    source: registry.redhat.io/openshift4/ose-sriov-operator-must-gather
  - mirrors:
    - quay.io/alosadag/rh-osbs-openshift-ose-sriov-network-operator-bundle
    source: registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-sriov-network-operator-bundle
  - mirrors:
    - quay.io/alosadag/openshift4-ose-sriov-dp-admission-controller
    source: registry.redhat.io/openshift4/ose-sriov-dp-admission-controller
  - mirrors:
    - quay.io/alosadag/openshift4-ose-sriov-infiniband-cni
    source: registry.redhat.io/openshift4/ose-sriov-infiniband-cni
  - mirrors:
    - quay.io/alosadag/openshift4-ose-ptp
    source: registry.redhat.io/openshift4/ose-ptp
  - mirrors:
    - quay.io/alosadag/openshift4-ose-sriov-network-device-plugin
    source: registry.redhat.io/openshift4/ose-sriov-network-device-plugin
  - mirrors:
    - quay.io/alosadag/openshift4-ose-sriov-network-config-daemon
    source: registry.redhat.io/openshift4/ose-sriov-network-config-daemon