apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: performance-addon-operator
  namespace: ztp-clusters
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - performance-addon-operator
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: base/operators/openshift-performance-addon-operator
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: performance-addon-operator
  name: performance-addon-operator-subscription-1
  namespace: ztp-clusters
spec:
  channel: ztp-clusters/ztp-repository
  placement:
    placementRef:
      kind: PlacementRule
      name: performance-addon-operator-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: performance-addon-operator
  name: performance-addon-operator-placement-1
  namespace: ztp-clusters
spec:
  clusterSelector:
    matchLabels:
      'pao': 'true'
