apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: vault-server
  namespace: ztp-clusters
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - vault-server
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: base/operators/vault-server
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: vault-server
  name: vault-server-subscription-1
  namespace: ztp-clusters
spec:
  channel: ztp-clusters/ztp-repository
  placement:
    placementRef:
      kind: PlacementRule
      name: hub-cluster
