apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: sno03
  namespace: sno03
  labels:
    agentclusterinstalls.extensions.hive.openshift.io/location: homelab
    networkType: static
spec:
  clusterRef:
    name: sno03
    namespace: sno03
  sshAuthorizedKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfjdWVDxtNZW5Mrb3lxfmison8iWG/diFyORcV7yKbPgzUQwk29GBbYjjR2RN5i/8Dud+SjZMGGZZtCLVO9uivHtfViC0Nu+vcTuFHgSOf/4aHxH2mYa5VYgwpAP5Ov/2lKkibM1CoF+noPdh+Gl8Izhc4ZTlNjOhG7jpVVgnd4WoK0tX5AiJ3fz3WYcDzZ4yQBNa/J43HP64l/6PX3CzgNGBVSbBHukYyzYHkIuFvSYPgnNW+dLrDx+uDypvnjYV5lYh+9jrW3lzMwiNQSzdDO30I6jupr8A05jtD5zA4maJDwUkAtcHVxc5Z2KEXlh7xWurES4amzScsHFSx3r2/NgzjD96h22BmPLN/tbZ19n21Bsb774b+vw0L471FFbsgkmiOYQcyNqcySFmeozsWixjxN2tG1VfqnH8pR189IYOX9e4YOHvYYV/5NzLjwIj2uLfGtqBOMdBGbMGyR/VeYyg9sz1nQ3mqs/sYo3OB0j+4TZeI9uJB4NZKoN4RjOc= stack@osp.home.lab
  agentLabelSelector:
    matchLabels:
      cluster-name: sno03
  pullSecretRef:
    name: pullsecret-cluster-sno03
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: sno03
