---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: spring-app
  namespace: openshift-gitops
  annotations:
    apps.open-cluster-management.io/reconcile-rate: low
spec:
  pathname: https://github.com/kskels/spring-app.git
  type: Git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: spring-app
  namespace: openshift-gitops
  labels:
    app: spring-app
  annotations:
    apps.open-cluster-management.io/github-path: deploy/rhacm
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: openshift-gitops/spring-app
  placement:
    placementRef:
      name: spring-app
      kind: PlacementRule
      group: apps.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: spring-app
  namespace: openshift-gitops
  labels:
    app: spring-app
spec:
  clusterSelector:
    matchExpressions:
      - key: sno
        operator: In
        values:
          - "true"
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: remote-spring-app
  namespace: openshift-gitops
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - spring-app
